### ISSUE TITLE
Administrator claims session scope not enabled?

### ISSUE THREAD

**Issue by seancorfield** [OpenBD/openbd-administrator#28]
Latest OpenBD source, latest Administrator source, Tomcat 7.0.42, ROOT web application:

https://www.dropbox.com/s/u5zfmo826ssn2po/Screenshot%202015-04-22%2018.14.58.png?dl=0

The requested SESSION scope is not enabled.
Request	/bluedragon/administrator/index.cfm
File Trace	/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/administrator/index.cfm
|
+-- /Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/administrator/Application.cfc
    |
    +-- /Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/adminapi/Administrator.cfc
Type	Application
Function(s)	onApplicationStart (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/administrator/Application.cfc, Line=32, Column=2)
|
+--setInitialSecurity (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/adminapi/Administrator.cfc, Line=30, Column=151)
Tag Context	CFSET (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/adminapi/Administrator.cfc, Line=46, Column=7)
|
+-- CFIF (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/adminapi/Administrator.cfc, Line=44, Column=5)
    |
    +-- CFFUNCTION (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/adminapi/Administrator.cfc, Line=30, Column=151)
        |
        +-- CFSCRIPT (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/administrator/Application.cfc, Line=33, Column=3)
            |
            +-- CFFUNCTION (/Developer/apache-tomcat-7.0.42/webapps/ROOT/bluedragon/administrator/Application.cfc, Line=32, Column=2)
Source	
43:     
44:     <cfif doSetConfig>
45:       
46:       <cfset session.auth.loggedIn = true />
47:       <cfset session.auth.password = localConfig.system.password />
^ Snippet from underlying CFML source

**Comment by arwilliamson** [comment]
Thanks @seancorfield i have recreated this bad boy ... looking into this now to see what is throwing this.

**Comment by seancorfield** [comment]
Excellent! Glad it's not me doing something stupid.

**Comment by arwilliamson** [comment]
Found the problem ... so we're in the in the onApplicationStart() phase of setting up the application.  At this point in the game, the session management hasn't been created for that particular user that has triggered the start of the application.  However, as part of the application setup, the code is setting stuff inside the session scope.

That is a little naughty, that should be done in the onSessionStart() because, if another user comes in to the administrator then they are technically not getting all the correct setup.  (i haven't really looked into the overall setup of this administrator application as this is not our code).

Let me have a thunk to see what the implications of setting up the session scope before onApplicationStart() is called - on first blush it feels 'wrong' to do that.  That shouldn't be in the context of any specific user.

I will however modify the administrator code here to move that to the onSessionStart() hook.
